seL4/seL4_libs

libsel4utils/include/sel4utils/serial_server/client.h
the libmuslc.git repository doesn't apparently define ssize_t unless sys/types is included,
or some posix specific define is present.
=> add sys/types.h for ssize_t

libsel4muslcsys/src/sys_morecore.c
This is useful when reseting components to their original state.
=> libsel4muslcsys: Expose morecore_top

libsel4platsupport/plat_include/am335x/sel4platsupport/plat/beaglebone.h, libsel4utils/include/sel4utils/sel4_zf_logif.h, libsel4vka/include/vka/object.h, libsel4vmm/src/vmm/vmm.c
make compile-all passes except for kzm_simulation_debug_xml_defconfig which also fails on my machine without this patch. All tests pass when running 'make simulate-x86_64' and when running the tests on a BeagleBone Black using config bbone_black_debug_xml_defconfig
=> Fixed clang warnings

libsel4platsupport/plat_include/zynqmp/sel4platsupport/plat/serial.h
This pull request adds AARCH32 and AARCH64 support for the Xilinx Zynq UltraScale+ MPSoC. Tested on the ZCU102 development board.
=> Zcu102 7.0.0

libsel4platsupport/src/sel4_arch/aarch64/crt0.S
Move the contents of the correct register to the stack pointer.
Signed-off-by: Robbie VanVossen <robert.vanvossen@dornerworks.com>
=> Fix for aarch64 crt0 in libsel4platsupport.

libsel4platsupport/plat_include/am335x/sel4platsupport/plat/cpsw.h, libsel4platsupport/src/plat/am335x/phy.c
The missing constants and functions are used in util_libs/libethdrivers and are needed in order to build for Beaglebone black.
Now, even after those missing macros & functions I still don't have the lwip+ethdriver working on BBB (yet), but at least I get it to build.
=> Added missing constants and functions for Beaglebone Black

libsel4utils/include/sel4utils/mcs_api.h
Small change to inline function api_tcb_set_sched_params to avoid warnings
=> Added UNUSED attribute to function

libsel4muslcsys/CMakeLists.txt, libsel4muslcsys/src/vsyscall.c
This initialises the C standard library using a constructor executed by the sel4runtime.
=> Use constructor to initialise libc

CMakeLists.txt, libsel4debug/include/sel4debug/debug.h, libsel4sync/CMakeLists.txt, libsel4sync/include/sync/bin_sem.h, libsel4sync/include/sync/condition_var.h, libsel4sync/include/sync/sem-bare.h, libsel4sync/include/sync/sem.h, libsel4sync/src/recursive_mutex.c, libsel4vka/CMakeLists.txt, libsel4vka/include/vka/vka.h
Signed-off-by: Axel Heider <axelheider@gmx.de>
=> debug: add helper functions to limit usage of magic numbers

libsel4bench/arch_include/arm/cpu/cortex-a72/sel4bench/cpu/events.h
This allows sel4bench for be build for RasPi4, see also https://github.com/seL4/seL4/pull/293
=> [RasPi4] Cortex-A72: add events.h

libsel4utils/include/sel4utils/vspace.h
Update the documented order of the vspace_root parameter
so that it matches the function signature
Signed-off-by: Kent McLeod <kent@kry10.com>
=> libsel4utils: Fix documentation bug

libsel4bench/arch_include/riscv/sel4bench/arch/sel4bench.h
I've tried to compile a CAmkES system for spike32, this fixed the build breaker.
=> libsel4bench: fix syntax errors for RISC-V rv32

libsel4utils/src/elf.c
This elfloading implementation guarantees that it doesn't leave
allocations behind in the loader allocators even if it fails. Fix area
where this doesn't occur.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> libsel4utils: Fix alloc leak in elf loading

libsel4vspace/src/arch/arm/mapping.c, libsel4vspace/src/arch/x86/mapping.c
The function `vspace_map_io()` is only used when `CONFIG_IOMMU` is defined, thus the clang build warning "control reaches end of non-void function [-Wreturn-type]" can be avoided easily when this function only exists when it is needed.
=> avoid build warning if CONFIG_IOMMU is not defined

libsel4vka/include/vka/object.h
`warning: mixture of designated and non-designated initializers in the same initializer list is a C99 extension [-Wc99-designator]`
```c
vka_object_t result = {.cptr = 0, .ut = 0, .type = 0, size_bits = 0};
```
This is a just typo that is harmless, but it's nicer to be consistent.
=> trivial: fix compiler warning

libsel4bench/arch_include/arm/armv/armv8-a/sel4bench/armv/sel4bench.h
If the cycle counter is disabled during a read, the operation can be preempted and lose the count of cycles for the duration of the preemption.
=> Do not disable counters when reading on aarch64

libsel4bench/arch_include/arm/cpu/cortex-a35/sel4bench/cpu/events.h
This closes #28 
Signed-off-by: Ben Leslie <benno@brkawy.com>
=> Add cpu/events.h header for Cortex-A35

libsel4debug/src/caps.c, libsel4serialserver/src/server.c
- Use seL4_Word printf modifier for seL4_CPtr type.
- Cast return value to (seL4_Error) as the API defines custom error
codes starting after the seL4_Error enum finishes.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> trivial: Fixup compiler warnings

libsel4muslcsys/src/sys_io.c
There we assert that the only file type admitted is FILE_TYPE_CPIO,
however libsel4camkes implements support to FILE_TYPE_SOCKET.
Signed-off-by: Carmelo Pintaudi <carmelo.pintaudi@hensoldt-cyber.de>
=> Remove assert in libsel4muslcsys/src/sys_io.c::sys_close()

libsel4utils/arch_include/riscv/sel4utils/arch/util.h, libsel4utils/sel4_arch_include/x86_64/sel4utils/sel4_arch/util.h
This include file is deprecated since 2016, and it seems there's nothing in there that is needed. Removing the reference here is a preparation to delete this file from the kernel includes completely, see https://github.com/seL4/seL4/issues/813
=> libsel4utils: remove obsolete includes

libsel4muslcsys/include/muslcsys/io.h, libsel4muslcsys/src/sys_io.c
CPIO data cannot be modified, it's basically ROM. The CPIO APIs have been changed some time back to use the const qualifier to properly reflect this. Add the const qualifier here also to avoid compiler warnings.
For example, this is the compiler warning with the FileServer from the VM examples:
```
.../libs/sel4_global_components/components/FileServer/src/server.c: In function ‘pre_init’:
.../libs/sel4_global_components/components/FileServer/src/server.c:34:63: warning: passing argument 3 of ‘muslcsys_install_cpio_interface’ from incompatible pointer type [-Wincompatible-pointer-types]
muslcsys_install_cpio_interface(_cpio_archive, cpio_size, cpio_get_file);
^~~~~~~~~~~~~
In file included from .../libs/sel4_global_components/components/FileServer/src/server.c:13: …
```
=> libsel4muslcsys: use const for CPIO data

libsel4muslcsys/src/sys_morecore.c
mmap creates mappings in multiples of the page size which is always at
least 4096. Assert that the return value is at least page size aligned.
Callers of mmap are allowed to assume that the memory returned is 4k
aligned and this can lead to subtle errors if non-aligned values are
returned.
=> libsel4muslcsys,mmap: Assert page aligned value

libsel4muslcsys/src/sys_morecore.c
It's invalid to return regions that are not page aligned. We round
lengths up to the nearest page size. munmap and mremmap are not
supported with static mmap and so we don't need to track this rounding
difference anywhere.
Signed-off-by: Kent McLeod <kent@kry10.com>
=> sel4muslcsys: Allocate aligned addr in static mmap

libsel4utils/include/sel4utils/mcs_api.h, libsel4utils/include/sel4utils/process_config.h, libsel4utils/include/sel4utils/thread_config.h
Use dedicated types instead of the generic uint64. Techically it does no make much difference, just improves the semantics a bit.
Test with: https://github.com/seL4/seL4/pull/922
=> libsel4utils: use seL4_Time instead of uint64_t

libsel4muslcsys/src/sys_morecore.c, libsel4muslcsys/src/syscalls.h, libsel4muslcsys/src/vsyscall.c
This commit adds a dummy __NR_munmap call, which prevents the "libsel4muslcsys: Error attempting syscall 215" error from printing.
That print shows up during the ARM VMM boot process.
=> muslcsys: implement dummy munmap call

libsel4bench/arch_include/arm/cpu/cortex-a55/sel4bench/cpu/events.h
Another fix for https://github.com/seL4/sel4bench/issues/32
This fixed the error
```
[182/299] Building C object apps/sel4bench/seL4_libs/libsel4bench/CMakeFiles/sel4bench.dir/src/arch/arm/armv/armv8-a/event_counters.c.obj
FAILED: apps/sel4bench/seL4_libs/libsel4bench/CMakeFiles/sel4bench.dir/src/arch/arm/armv/armv8-a/event_counters.c.obj
/usr/bin/ccache /usr/bin/aarch64-linux-gnu-gcc --sysroot=/github/workspace/build  -I/github/workspace/projects/seL4_libs/libsel4bench/include -I/github/workspace/projects/seL4_libs/libsel4bench/arch_include/arm/armv/armv8-a -I/github/workspace/projects/seL4_libs/libsel4bench/arch_include/arm/cpu/cortex-a55 -I/github/workspace/projects/seL4_libs/libsel4bench/sel4_arch_include/aarch64 -I/github/workspace/projects/seL4_libs/libsel4bench/arch_include/arm …
```
=> libsel4bench: add support for ARM Cortex-A55

libsel4allocman/src/allocman.c
If either allocman_configure_mspace_reserve or
allocman_configure_utspace_reserve returns early it still needs to
end the started operation otherwise the allocator will be left in an
invalid state leading to it's watermarks never being refilled.
=> allocman: Add missing calls to _end_operation

libsel4allocman/sel4_arch/aarch64/allocman/sel4_arch/reservation.h, libsel4allocman/src/bootstrap.c, libsel4vka/arch_include/arm/vka/arch/object.h, libsel4vka/sel4_arch_include/aarch32/vka/sel4_arch/object.h, libsel4vka/sel4_arch_include/aarch64/vka/sel4_arch/kobject_t.h, libsel4vka/sel4_arch_include/aarch64/vka/sel4_arch/object.h
These changes are required to support the proposed changes in https://github.com/seL4/seL4/pull/801.
Test with: https://github.com/seL4/seL4/pull/801
Test with: https://github.com/seL4/sel4test/pull/100
=> RFC: AArch64: remove VSpace object types, seL4_ARM_PageDirectory and seL4_ARM_PageUpperDirectory

libsel4simple-default/src/libsel4simple-default.c, libsel4simple/arch_include/arm/simple/arch/simple.h, libsel4simple/arch_include/x86/simple/arch/simple.h
Make sure this macro is defined based on all possible configurations.
Required based on this change: https://github.com/seL4/seL4/pull/1088
=> simple: Define SIMPLE_SKIPPED_INIT_CAPS better

libsel4simple-default/src/libsel4simple-default.c, libsel4simple/arch_include/arm/simple/arch/simple.h, libsel4simple/arch_include/x86/simple/arch/simple.h, libsel4test/include/sel4test/test.h
This allows tests to have the initial smc cap when that support is enabled.
This is required for the new SMC test here: https://github.com/seL4/sel4test/pull/85
=> libsel4test: Add smc cap to test env

libsel4muslcsys/src/vsyscall.c
libsel4muslcsys: fix va list leak in failure case
va_start/va_end should call in pair
=> libsel4muslcsys: fix va list leak in failure case

libsel4utils/src/irq_server/irq_server.c
libsel4utils: fix use of uninitialized value
thread_created maybe uninitialized if failure before initialize
=> libsel4utils: fix use of uninitialized value

libsel4utils/src/irq_server/irq_server.c
libsel4utils: fix null pointer reference
add sanity check after alloc irq_server_t
=> libsel4utils: fix null pointer reference

libsel4platsupport/src/io.c
libsel4platsupport: check num_pages after alloc success
To avoid null pointer reference
=> libsel4platsupport: check num_pages after alloc success

.github/workflows/sel4test-sim.yml
Similar to https://github.com/seL4/seL4/pull/1154, pick up things from https://github.com/seL4/ci-actions/pull/297
=> CI: simulation and HW build with LLVM on RISCV

libsel4allocman/src/allocman.c
Clang does a few more checks than gcc for the `prinf()` parameters and raises some warning for 64-bit. See e.g. https://github.com/axel-h/seL4_libs/actions/runs/6975395333/job/18982455268?pr=5
```
/github/workspace/projects/seL4_libs/libsel4allocman/src/allocman.c:525:98: warning: format specifies type 'int' but the argument has type 'seL4_Word' (aka 'unsigned long') [-Wformat]
ZF_LOGE("Failed to set reserve for {type: %d size_bits: %d} as one already exists.", chunk.type, chunk.size_bits);
~~                                         ^~~~~~~~~~
%lu
/github/workspace/projects/util_libs/libutils/include/utils/zf_log.h:359:43: note: expanded from macro 'ZF_LOGE'
_ZF_LOG_IMP(ZF_LOG_ERROR, _ZF_LOG_TAG, __VA_ARGS__)
^~~~~~~~~~~
/github/workspace/projects/util_libs/libutils/include/utils/zf_log.h: …
```
=> libsel4allocman: fix clang warnings for printing

.github/workflows/sel4test-sim.yml
Fix copy/paste bug with the name. Has been there thing the beginnin, see 99b96310
=> CI: use proper step name

libsel4utils/src/process.c
libsel4utils: remove unused environment setup
It is unnecessary to writing environment to the stack since the target environment size is always 0.
This PR also fix compile warning on native X86 build:
```
[2/8] Building C object apps/sel4test-driver/seL4_libs/libsel4utils/CMakeFiles/sel4utils.dir/src/process.c.obj
/home/archer/code/sel4/projects/seL4_libs/libsel4utils/src/process.c: In function ‘sel4utils_spawn_process_v’:
/home/archer/code/sel4/projects/seL4_libs/libsel4utils/src/process.c:320:13: warning: ‘sel4utils_stack_copy_args’ accessing 8 bytes in a region of size 0 [-Wstringop-overflow=]
320 |     error = sel4utils_stack_copy_args(vspace, &process->vspace, vka, envc, envp, dest_envp, &initial_stack_pointer);
| …
```
=> libsel4utils: remove unused environment setup

libsel4platsupport/src/common.c
Caused by recursive stdio function calling.
Just use seL4_DebugPutString() directly to avoid any problems.
=> Avoid garbage on stdout for first print

libsel4bench/arch_include/arm/armv/armv7-a/sel4bench/armv/sel4bench.h
The same scenario as for aarch64: If the cycle counter is disabled during a read, the operation can be preempted and lose the count of cycles for the duration of the preemption.
Closes Issue: #34
=> sel4bench: Do not disable counters for armv7-a.

CMakeLists.txt, libsel4allocman/CMakeLists.txt, libsel4bench/CMakeLists.txt, libsel4debug/CMakeLists.txt, libsel4muslcsys/CMakeLists.txt, libsel4platsupport/CMakeLists.txt, libsel4serialserver/CMakeLists.txt, libsel4simple-default/CMakeLists.txt, libsel4simple/CMakeLists.txt, libsel4sync/CMakeLists.txt, libsel4test/CMakeLists.txt, libsel4utils/CMakeLists.txt, libsel4vka/CMakeLists.txt, libsel4vspace/CMakeLists.txt
Compatibility with versions <3.10 is going away.
As it happens, we're not using any CMake features that have changed between 3.7 and 3.16, so bump the lowest version to 3.16.
=> Bump minimum CMake version

libsel4muslcsys/CMakeLists.txt, libsel4muslcsys/src/sys_io.c, libsel4muslcsys/src/vsyscall.c
riscv32 linux abi doesn't define lseek. Instead llseek uses 2 32bit arguments for a 64bit offset and returns the value via a pointer to 64bit value in user memory.
Instead of calling a syscall within a syscall, just make a shared internal function to call for both lseek and llseek.
=> sel4muslcsys: Fix up llseek on 32bit arch

libsel4muslcsys/src/sys_morecore.c
mmap is expected to return an error if a length of 0 is ever requested.
The caller is likely doing something wrong if a 0 length is requested and it leads for hard to find bugs if we just return the current address of the end of available memory.
=> libsel4muslcsys: Return error if 0 len requested

libsel4platsupport/src/timer.c
If there is no ltimer for a particular platform, then these functions do not exist, so make the init_default_timer_ops() always return errors.
The intended way to avoid this is to not use the timer when
CONFIG_LIB_PLAT_SUPPORT_NO_PLATFORM_LTIMER
is set.
https://github.com/seL4/sel4bench/pull/55
=> libsel4platsupport: don't link a nonexistent ltimer

libsel4platsupport/src/timer.c
As suggested by Indan to be clearer to understand. https://github.com/seL4/util_libs/pull/196#issuecomment-2918974119.
Depends on https://github.com/seL4/util_libs/pull/197.
Test with: https://github.com/seL4/util_libs/pull/197
Test with: https://github.com/seL4/sel4bench/pull/58
=> use LibPlatSupportHaveTimer instead of inverse

libsel4test/include/sel4test/test.h
Commit 1:
This would previously fail at runtime, but we can fail the build
instead and catch this earlier.
In file included from /src/helpers.h:13,
from /src/tests/ipc.c:13:
/projects/sel4test/apps/sel4test-tests/src/tests/ipc.c:
In function ‘test_ipc_pair’:
/projects/seL4_libs/libsel4test/include/sel4test/test.h:243:10:
error: static assertion failed: "sizeof(res) does not match
sizeof(SUCCESS), use of test_eq incorrect"
243 |          _Static_assert(sizeof(_a) == sizeof(_b), \
|          ^~~~~~~~~~~~~~
/projects/seL4_libs/libsel4test/include/sel4test/test.h:270:24:
note: in expansion of macro ‘test_op’
270 | #define test_eq(a, b)  test_op(a, b, ==)
|                        ^~~~~~~
/projects/sel4test/apps/sel4test-tests/src/tests/ipc.c:347:25:
note: in expansion of macro ‘test_eq’
347 | …
=> libsel4test: static_assert sizeof() mismatches & check against unsigned char support
